"""empty message

Revision ID: 08b6e4137a75
Revises: fcaaca6c9ee8
Create Date: 2022-12-31 00:41:54.455915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08b6e4137a75"
down_revision = "fcaaca6c9ee8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
