"""empty message

Revision ID: 64dfc8db5bec
Revises: bdd9f60bb9b6
Create Date: 2022-12-31 14:50:31.503068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64dfc8db5bec"
down_revision = "bdd9f60bb9b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stripe_id", sa.String(), nullable=True))
        batch_op.alter_column(
            "price",
            existing_type=sa.REAL(),
            type_=sa.Float(precision=2),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(precision=2),
            type_=sa.REAL(),
            existing_nullable=False,
        )
        batch_op.drop_column("stripe_id")

    # ### end Alembic commands ###
